---
# handlers file for db
- name: Restart Redis
  service:
    name: redis
    state: restarted

- name: Start Redis
  service:
    name: redis
    state: started

- name: Stop Redis
  service:
    name: redis
    state: stopped

- name: Enable Redis
  service:
    name: redis
    enabled: yes
- name: Start Postgresql
  service:
    name: postgresql
    state: started
- name: Stop postgresql
  service:
    name: postgresql
    state: stopped
